### ISSUE TITLE
Error !] [ABORT]: Operative System => 

### ISSUE THREAD

**Issue by id2746** [r00t-3xp10it/msf-auxiliarys#5]
Hi!
Got mistake (Wsearch.rb):
_!] [ABORT]: Operative System => Windows 7 (Build 7601, Service Pack 1).
[-] Only windows systems are supported by this module...
[-] Please execute [info] for further information...

[-] Post failed: Rex::Script::Completed Rex::Script::Completed
[-] Call stack:
[-] /usr/share/metasploit-framework/modules/post/windows/escalate/Wsearch.rb:158:in `unsupported'
[-] /usr/share/metasploit-framework/modules/post/windows/escalate/Wsearch.rb:420:in `run'
Post module execution completed_

Tested on win7 x64.
What's wrong?

**Comment by r00t-3xp10it** [comment]
this vuln was been allready patched ..
and it depends of system build ..

**HINT: that post-module its not on my repository, because of that ..**

here you have some '**privilege escalation'** modules (way better)...
https://github.com/r00t-3xp10it/msf-auxiliarys/tree/master/local%20privilege%20escalation
HINT: I recomend 'enigma_fileless_uac_bypass' ...

**Comment by id2746** [comment]
Thank you!
